Nutrition_task:
  description: >
    Create a customized meal plan for the trainee based on the following:
    - Metrics : {metrics}
    - Fitness goal: {fitness_goal} (e.g., muscle gain, fat loss, maintenance)
    - Dietary preferences/restrictions: {dietary_preferences}
  expected_output: >
    A detailed 7-day meal plan including:
    - Macronutrient breakdown for each meal.
    - Suggested recipes or simple meal ideas.
    - Pre- and post-workout meal suggestions.
    - Hydration tips.
    Formatted as markdown without '```'.
  agent: nutrition_specialist
